version: '3.8'
services:
  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      - OLLAMA_URL=http://ollama:11434
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
      - SUPABASE_PROJECT_URL=${SUPABASE_PROJECT_URL}
      - PROJECT_URL=${PROJECT_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - ollama
    restart: unless-stopped

  frontend:
    build: ./frontend
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  ollama_data:
